# Generated by Django 2.0.5 on 2018-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IwantToSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('words', models.CharField(max_length=1000)),
                ('animated', models.CharField(choices=[('fadeIn', 'fade in'), ('bounceIn', 'bounce in'), ('fadeInDown', 'fade in down'), ('fadeInUp', 'fade in up'), ('fadeInLeft', 'fade in left'), ('fadeInRight', 'fade in right'), ('rollIn', 'roll in')], max_length=20)),
            ],
        ),
    ]
